//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM_Software {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATM_Software.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _11111 {
            get {
                object obj = ResourceManager.GetObject("_11111", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जमा राशि.
        /// </summary>
        internal static string Account_Balance {
            get {
                return ResourceManager.GetString("Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खाता चुनें.
        /// </summary>
        internal static string ActLabel {
            get {
                return ResourceManager.GetString("ActLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रद्द करें.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिन परिवर्तन कन्फ़र्म करें.
        /// </summary>
        internal static string CcpLabel {
            get {
                return ResourceManager.GetString("CcpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिन परिवर्तन.
        /// </summary>
        internal static string Change_Pin {
            get {
                return ResourceManager.GetString("Change_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कन्फ़र्म.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्रेडिट कार्ड.
        /// </summary>
        internal static string CreditCrd {
            get {
                return ResourceManager.GetString("CreditCrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालू खाता.
        /// </summary>
        internal static string CurrentAcc {
            get {
                return ResourceManager.GetString("CurrentAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to राशी डालें.
        /// </summary>
        internal static string EaLabel {
            get {
                return ResourceManager.GetString("EaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिन दर्ज करें.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिन रीसेट करें.
        /// </summary>
        internal static string ForgotPin {
            get {
                return ResourceManager.GetString("ForgotPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजेक्शन चुनें.
        /// </summary>
        internal static string MainLable {
            get {
                return ResourceManager.GetString("MainLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनी स्टेटमेंट.
        /// </summary>
        internal static string Mini_Statement {
            get {
                return ResourceManager.GetString("Mini_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बचत खाता.
        /// </summary>
        internal static string SavingsAcc {
            get {
                return ResourceManager.GetString("SavingsAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आहरण.
        /// </summary>
        internal static string Withdrawal {
            get {
                return ResourceManager.GetString("Withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yess {
            get {
                object obj = ResourceManager.GetObject("yess", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
